name: Create Releasable Package Drop

on:
  push:
    branches:
      - release-*

permissions:
  contents: read

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |
        npm --version
        # corepack enable npm
        npm install -g $(jq -r '.packageManager' < package.json)
        npm --version
    - name: npm install and test
      run: |
        npm ci
        npm test
    - name: Adding playwright
      run: npm install --no-save --no-package-lock playwright
    - name: Validate the browser can import TypeScript
      run: npx hereby test-browser-integration
    - name: LKG, clean, and pack
      run: |
        npx hereby LKG
        npx hereby clean
        npm pack ./
        mv typescript-*.tgz typescript.tgz
    - name: Upload built tarfile
      uses: actions/upload-artifact@v3
      with:
        name: tgz
        path: typescript.tgz
